# =============================================================================
# CATEGORIES & COURSE TITLES
# =============================================================================

CATEGORY_TREE = {
  'Công nghệ thông tin' => %w[Web\ Development Frontend Backend Mobile\ Development Database Security],
  'AI & Machine Learning' => ['Machine Learning', 'Deep Learning', 'LLM', 'Prompt\ Engineering',
                               'Computer\ Vision', 'NLP', 'AI\ Agent', 'RAG\ Systems'],
  'Data' => ['Data\ Science', 'Data\ Engineering', 'Business\ Intelligence', 'Data\ Analytics'],
  'DevOps & Cloud' => %w[DevOps Cloud Kubernetes Infrastructure\ as\ Code Monitoring],
  'Lập trình' => ['Python', 'JavaScript/TypeScript', 'Go', 'Rust', 'Java', 'C/C++', 'Ruby'],
  'Ngoại ngữ' => ['Tiếng\ Anh', 'IELTS\ &\ TOEIC', 'Tiếng\ Nhật', 'Tiếng\ Hàn',
                   'Tiếng\ Trung', 'Business\ English', 'Tiếng\ Pháp'],
  'Tài chính & Đầu tư' => ['Đầu\ tư\ chứng\ khoán', 'Phân\ tích\ kỹ\ thuật',
                             'Phân\ tích\ cơ\ bản', 'Quản\ lý\ tài\ chính\ cá\ nhân',
                             'Kế\ toán\ &\ Thuế', 'Tài\ chính\ doanh\ nghiệp'],
  'Marketing & Kinh doanh' => ['Digital\ Marketing', 'SEO\ &\ SEM', 'Social\ Media\ Marketing',
                                'Content\ Marketing', 'Email\ Marketing', 'Brand\ Management'],
  'Thiết kế' => ['UI/UX\ Design', 'Graphic\ Design', 'Motion\ Design',
                  'Product\ Design', 'Brand\ Identity'],
  'Đa phương tiện' => ['Video\ Editing', 'Photography', 'Podcast\ &\ Audio',
                        'After\ Effects', '3D\ Design'],
  'Product & Business' => ['Product\ Management', 'Business\ Strategy',
                             'Lean\ Startup', 'Project\ Management', 'Agile\ &\ Scrum'],
  'Khoa học & Kỹ thuật' => ['Robotics', 'IoT', 'Arduino\ &\ Raspberry\ Pi', 'Cơ\ điện\ tử'],
  'Phát triển bản thân' => ['Kỹ\ năng\ giao\ tiếp', 'Tư\ duy\ phản\ biện',
                              'Quản\ lý\ thời\ gian', 'Leadership', 'Emotional\ Intelligence'],
}.freeze

# Flatten to array with parent_id logic (built at runtime)
CATEGORY_FLAT = [
  # Main categories
  { key: 'CNTT',   name: 'Công nghệ thông tin',   parent: nil },
  { key: 'AI',     name: 'AI & Machine Learning',  parent: nil },
  { key: 'DATA',   name: 'Data & Analytics',       parent: nil },
  { key: 'DEVOPS', name: 'DevOps & Cloud',         parent: nil },
  { key: 'LAPTRN', name: 'Lập trình',              parent: nil },
  { key: 'NNGU',   name: 'Ngoại ngữ',             parent: nil },
  { key: 'TAICHINH', name: 'Tài chính & Đầu tư',  parent: nil },
  { key: 'MKTG',   name: 'Marketing & Kinh doanh', parent: nil },
  { key: 'DESIGN', name: 'Thiết kế',               parent: nil },
  { key: 'MEDIA',  name: 'Đa phương tiện',         parent: nil },
  { key: 'PRODUCT', name: 'Product & Business',    parent: nil },
  { key: 'SCIENCE', name: 'Khoa học & Kỹ thuật',  parent: nil },
  { key: 'SOFT',   name: 'Phát triển bản thân',    parent: nil },
  # Subs CNTT
  { key: 'WEBDEV',   name: 'Web Development',       parent: 'CNTT' },
  { key: 'FRONTEND', name: 'Frontend',              parent: 'CNTT' },
  { key: 'BACKEND',  name: 'Backend',               parent: 'CNTT' },
  { key: 'MOBILE',   name: 'Mobile Development',    parent: 'CNTT' },
  { key: 'DB',       name: 'Database',              parent: 'CNTT' },
  { key: 'SECURITY', name: 'Bảo mật & An toàn',    parent: 'CNTT' },
  # Subs AI
  { key: 'ML',       name: 'Machine Learning',      parent: 'AI' },
  { key: 'DL',       name: 'Deep Learning',         parent: 'AI' },
  { key: 'LLM',      name: 'LLM & Generative AI',   parent: 'AI' },
  { key: 'PE',       name: 'Prompt Engineering',    parent: 'AI' },
  { key: 'CV',       name: 'Computer Vision',       parent: 'AI' },
  { key: 'NLP',      name: 'NLP',                   parent: 'AI' },
  { key: 'AGENT',    name: 'AI Agent',              parent: 'AI' },
  { key: 'RAG',      name: 'RAG Systems',           parent: 'AI' },
  # Subs DATA
  { key: 'DS',       name: 'Data Science',          parent: 'DATA' },
  { key: 'DE',       name: 'Data Engineering',      parent: 'DATA' },
  { key: 'BI',       name: 'Business Intelligence', parent: 'DATA' },
  { key: 'DA',       name: 'Data Analytics',        parent: 'DATA' },
  # Subs DEVOPS
  { key: 'DEVOPSUB', name: 'DevOps',                parent: 'DEVOPS' },
  { key: 'CLOUD',    name: 'Cloud Computing',       parent: 'DEVOPS' },
  { key: 'K8S',      name: 'Kubernetes',            parent: 'DEVOPS' },
  { key: 'IaC',      name: 'Infrastructure as Code',parent: 'DEVOPS' },
  # Subs LAPTRN
  { key: 'PYTHON',   name: 'Python',                parent: 'LAPTRN' },
  { key: 'JSTYPE',   name: 'JavaScript/TypeScript', parent: 'LAPTRN' },
  { key: 'GO',       name: 'Go Language',           parent: 'LAPTRN' },
  { key: 'RUST',     name: 'Rust',                  parent: 'LAPTRN' },
  { key: 'JAVA',     name: 'Java & Spring Boot',    parent: 'LAPTRN' },
  { key: 'RUBY',     name: 'Ruby on Rails',         parent: 'LAPTRN' },
  # Subs NNGU
  { key: 'ENG',      name: 'Tiếng Anh',             parent: 'NNGU' },
  { key: 'IELTS',    name: 'IELTS & TOEIC',         parent: 'NNGU' },
  { key: 'JPN',      name: 'Tiếng Nhật',            parent: 'NNGU' },
  { key: 'KOR',      name: 'Tiếng Hàn',             parent: 'NNGU' },
  { key: 'CHN',      name: 'Tiếng Trung',           parent: 'NNGU' },
  { key: 'BIZENG',   name: 'Business English',      parent: 'NNGU' },
  # Subs TAICHINH
  { key: 'STOCKS',   name: 'Đầu tư chứng khoán',   parent: 'TAICHINH' },
  { key: 'TA',       name: 'Phân tích kỹ thuật',    parent: 'TAICHINH' },
  { key: 'FA',       name: 'Phân tích cơ bản',      parent: 'TAICHINH' },
  { key: 'PF',       name: 'Tài chính cá nhân',     parent: 'TAICHINH' },
  { key: 'ACCTG',    name: 'Kế toán & Thuế',        parent: 'TAICHINH' },
  # Subs MKTG
  { key: 'DMKTG',    name: 'Digital Marketing',     parent: 'MKTG' },
  { key: 'SEO',      name: 'SEO & SEM',             parent: 'MKTG' },
  { key: 'SMM',      name: 'Social Media',          parent: 'MKTG' },
  { key: 'CONTENT',  name: 'Content Marketing',     parent: 'MKTG' },
  { key: 'BRAND',    name: 'Brand Management',      parent: 'MKTG' },
  # Subs DESIGN
  { key: 'UXUI',     name: 'UI/UX Design',          parent: 'DESIGN' },
  { key: 'GDESIGN',  name: 'Graphic Design',        parent: 'DESIGN' },
  { key: 'MOTION',   name: 'Motion Design',         parent: 'DESIGN' },
  { key: 'PDESIGN',  name: 'Product Design',        parent: 'DESIGN' },
  # Subs MEDIA
  { key: 'VIDED',    name: 'Video Editing',         parent: 'MEDIA' },
  { key: 'PHOTO',    name: 'Photography',           parent: 'MEDIA' },
  { key: 'SOUND',    name: 'Podcast & Audio',       parent: 'MEDIA' },
  # Subs PRODUCT
  { key: 'PM',       name: 'Product Management',    parent: 'PRODUCT' },
  { key: 'BIZSTRAT', name: 'Business Strategy',     parent: 'PRODUCT' },
  { key: 'PROJMGMT', name: 'Project Management',    parent: 'PRODUCT' },
  { key: 'AGILE',    name: 'Agile & Scrum',         parent: 'PRODUCT' },
  # Subs SCIENCE
  { key: 'ROBOT',    name: 'Robotics',              parent: 'SCIENCE' },
  { key: 'IOT',      name: 'IoT',                   parent: 'SCIENCE' },
  # Subs SOFT
  { key: 'COMM',     name: 'Kỹ năng giao tiếp',    parent: 'SOFT' },
  { key: 'LEADER',   name: 'Leadership',            parent: 'SOFT' },
  { key: 'MINDSET',  name: 'Tư duy & Mindset',     parent: 'SOFT' },
].freeze

# ── COURSE TITLE POOLS (by category key) ─────────────────────────────────────
COURSE_POOL = {
  'ML' => [
    ['Machine Learning A-Z™: Python & R trong Khoa học Dữ liệu', 'Từ Linear Regression đến Neural Networks, master toàn bộ thuật toán ML với Python và R thực chiến.'],
    ['Scikit-Learn Masterclass: Feature Engineering & Model Selection', 'Pipeline, cross-validation, hyperparameter tuning và model deployment đầy đủ.'],
    ['ML Production: MLflow, Airflow và Triển khai Mô hình', 'Xây dựng end-to-end ML system: versioning, monitoring và serving trên cloud.'],
    ['Ensemble Methods: Random Forest, XGBoost và LightGBM', 'Thuật toán ensemble mạnh nhất trong thực tế, từ lý thuyết đến Kaggle competition.'],
    ['Unsupervised Learning: Clustering, PCA và Anomaly Detection', 'K-Means, DBSCAN, Autoencoders và ứng dụng trong fraud detection.'],
    ['Time Series Forecasting: ARIMA, Prophet và LSTM', 'Phân tích và dự báo chuỗi thời gian cho tài chính và vận hành.'],
    ['Interpretable Machine Learning: SHAP, LIME và Fairness', 'Giải thích mô hình AI cho stakeholder phi kỹ thuật, đạo đức AI.'],
    ['Applied ML for Business: Từ Use Case đến ROI', 'Xác định bài toán kinh doanh, build model và đo giá trị thực tế.'],
  ],
  'DL' => [
    ['Deep Learning với TensorFlow 2.0 và Keras: Toàn diện', 'CNN, RNN, LSTM, Transformers, GAN — đầy đủ kiến trúc với TF2 và Keras.'],
    ['PyTorch for Deep Learning: Từ Tensor đến Production', 'DataLoader, custom modules, distributed training và ONNX export.'],
    ['Convolutional Neural Networks for Computer Vision', 'ResNet, EfficientNet, YOLO — xây dựng từ scratch và fine-tuning.'],
    ['Recurrent Neural Networks & LSTM: NLP và Time Series', 'Sequence modeling, attention mechanism và encoder-decoder architecture.'],
    ['Generative Adversarial Networks: StyleGAN và Diffusion Models', 'GANs từ DCGAN đến StyleGAN3, DDPM và Stable Diffusion fine-tuning.'],
    ['Transfer Learning & Fine-tuning: ImageNet đến Production', 'Chiến lược freeze layers, learning rate scheduling và domain adaptation.'],
    ['Neural Architecture Search và AutoML', 'NAS với Optuna, AutoKeras — tự động tìm kiến trúc tối ưu.'],
  ],
  'LLM' => [
    ['Xây dựng Ứng dụng AI với GPT-4 và LangChain từ Zero', 'Chatbot, agent, RAG pipeline — production-ready với LangChain và OpenAI API.'],
    ['Fine-tuning LLMs với LoRA và QLoRA trên GPU Tiêu thụ thấp', 'Alpaca, Vicuna, Llama-2 fine-tuning với PEFT trên laptop hoặc Colab.'],
    ['RAG Production: Xây dựng AI Knowledge Base cho Doanh nghiệp', 'Vector DB, embedding, reranking, query decomposition — enterprise grade.'],
    ['LangGraph: Xây dựng Agentic Workflows và Stateful AI', 'Graph-based agent orchestration, checkpointing và human-in-the-loop.'],
    ['LLM Evaluation & Safety: Red Teaming và Guardrails', 'Benchmark frameworks, hallucination detection, RLHF và constitutional AI.'],
    ['Building Local LLMs: Ollama, LM Studio và vLLM', 'Self-hosted AI với Llama 3, Mistral, Qwen — inference optimization.'],
    ['Multimodal AI: GPT-4V, LLaVA và Vision-Language Models', 'Image captioning, visual QA và document understanding với VLMs.'],
  ],
  'PE' => [
    ['Prompt Engineering Masterclass: Chain-of-Thought đến ReAct', 'Few-shot, CoT, Self-Consistency, ReAct và các kỹ thuật prompting nâng cao.'],
    ['AI Productivity: ChatGPT, Claude và Gemini cho Người đi làm', 'Tăng 10x năng suất với AI — từ viết lách đến phân tích dữ liệu.'],
    ['Prompt Engineering cho Developer: LLM Integration Patterns', 'Function calling, structured output, tool use và prompt versioning.'],
  ],
  'CV' => [
    ['Computer Vision với OpenCV và Python: Toàn diện', 'Image processing, feature detection, tracking và real-time video analysis.'],
    ['Object Detection: YOLOv8 từ Training đến Edge Deployment', 'Custom dataset, Roboflow annotation, TensorRT và Raspberry Pi deployment.'],
    ['Image Segmentation: SAM, Detectron2 và Mask R-CNN', 'Semantic, instance và panoptic segmentation cho production.'],
    ['3D Vision: Point Cloud và NeRF', 'LiDAR processing với Open3D, NeRF và Gaussian Splatting.'],
  ],
  'NLP' => [
    ['NLP với Python: Từ Tokenization đến BERT Classifier', 'spaCy, HuggingFace Transformers, Named Entity Recognition và text classification.'],
    ['Vietnamese NLP: Xử lý Ngôn ngữ tự nhiên Tiếng Việt', 'PhoBERT, VnCoreNLP, word segmentation và Vietnamese corpus building.'],
    ['Information Extraction: NER, Relation và Event Extraction', 'Annotate, train và deploy IE systems cho tài liệu kinh doanh.'],
  ],
  'AGENT' => [
    ['Building AI Agents với LangGraph và CrewAI', 'Multi-agent systems, tool calling, memory và long-horizon task automation.'],
    ['AutoGen: Multi-Agent Conversation Framework', 'Code generation agents, planner-executor pattern và human feedback loop.'],
    ['AI Agent cho Tự động hóa Công việc: Thực chiến', 'Browse, code, email và calendar agents cho office automation.'],
  ],
  'RAG' => [
    ['RAG từ cơ bản đến Nâng cao: Pinecone, Weaviate và pgvector', 'Chunking strategies, hybrid search, reranking và evaluation với RAGAs.'],
    ['GraphRAG: Knowledge Graph kết hợp RAG', 'Neo4j, entity extraction và graph traversal cho complex reasoning.'],
  ],
  'WEBDEV' => [
    ['Full-Stack Web Development: React 18, Node.js và PostgreSQL', 'Xây dựng SaaS app hoàn chỉnh từ auth đến payment và deployment.'],
    ['Ruby on Rails 7: Xây dựng Web App Chuyên nghiệp', 'Turbo, Stimulus, Hotwire — modern Rails với Action Cable và Solid Queue.'],
    ['Django 5 & DRF: Backend Web Development Toàn diện', 'REST API, authentication, celery, channels và deployment trên AWS.'],
    ['Spring Boot 3 & React: Enterprise Web Development', 'Microservices với Spring Cloud, Security OAuth2 và React frontend.'],
    ['Laravel 11 & Livewire: Full-Stack PHP Modern', 'Livewire 3, Filament admin panel và Laravel Octane cho performance.'],
    ['FastAPI + React: Modern API-First Development', 'Async Python, Pydantic v2, SQLModel và React Query integration.'],
    ['Nuxt 3 & Vue.js 3: Full-Stack JavaScript Masterclass', 'Server-side rendering, Nitro, Supabase và Vercel/Netlify deployment.'],
  ],
  'FRONTEND' => [
    ['React 18 và TypeScript: Advanced Patterns và Architecture', 'Server Components, Suspense, concurrent rendering và design patterns.'],
    ['Next.js 14: App Router, Server Actions và Edge Runtime', 'RSC, streaming, caching strategies và Vercel deployment optimizations.'],
    ['Vue.js 3 Composition API và Pinia: Masterclass', 'Composables, teleport, suspense, Vue Query và state management patterns.'],
    ['Angular 17: Enterprise Frontend Development', 'Signals, standalone components, new control flow và Zone-less change detection.'],
    ['CSS Mastery: Modern Layout, Animations và Design Systems', 'Flexbox, Grid, container queries, @layer và design token architecture.'],
    ['Web Performance: Core Web Vitals và Browser Optimization', 'LCP, INP, CLS — từ DevTools profiling đến performance budget.'],
    ['Testing React Applications: Vitest, RTL và Playwright', 'Unit, integration và E2E testing với mock strategies và CI integration.'],
  ],
  'BACKEND' => [
    ['Node.js & Express: Backend Development Chuyên nghiệp', 'REST API, JWT auth, WebSocket, Prisma ORM và Docker deployment.'],
    ['Python FastAPI: Xây dựng High-Performance APIs', 'Async/await, dependency injection, SQLAlchemy 2.0 và OpenAPI docs.'],
    ['Go Programming: Backend Development từ Cơ bản đến Production', 'Goroutines, channels, gin, sqlx, graceful shutdown và tracing.'],
    ['Rust cho Web: Axum và SeaORM Backend Development', 'Ownership, traits, async Rust, tower middleware và postgres integration.'],
    ['Microservices: gRPC, Kafka và API Gateway Pattern', 'Service mesh, circuit breaker, saga pattern và distributed tracing.'],
    ['GraphQL API: Schema Design và Performance', 'Apollo Server, DataLoader, subscriptions và federation architecture.'],
  ],
  'MOBILE' => [
    ['Flutter & Dart: Xây dựng iOS và Android App Thương mại', 'BLoC, Riverpod, Firebase integration và App Store/Play Store deployment.'],
    ['React Native: Cross-Platform Mobile với TypeScript', 'Expo Router, Zustand, React Native Reanimated và Expo EAS Build.'],
    ['SwiftUI: iOS Development Từ Zero đến App Store', 'MVVM, Combine, Swift Concurrency và WidgetKit cho iOS 17.'],
    ['Jetpack Compose & Kotlin: Modern Android Development', 'Material 3, Coroutines, Hilt DI và Google Play deployment workflow.'],
    ['Kotlin Multiplatform Mobile: Shared Logic iOS & Android', 'KMP với Compose Multiplatform, Ktor và SQLDelight cross-platform DB.'],
  ],
  'DB' => [
    ['SQL Masterclass: PostgreSQL Performance Tuning', 'Query optimization, EXPLAIN ANALYZE, indexing strategies và partitioning.'],
    ['MySQL 8: Administration và Performance Engineering', 'InnoDB internals, replication, ProxySQL và schema migration strategies.'],
    ['MongoDB: NoSQL Modeling và Aggregation Pipeline', 'Schema design patterns, Atlas Search, Change Streams và transactions.'],
    ['Redis: Caching, Pub/Sub và Distributed Lock', 'Data structures, cluster mode, Redis Streams và cache invalidation.'],
    ['Elasticsearch: Search Architecture và Analytics', 'Mapping, query DSL, aggregations, ECS và Kibana dashboarding.'],
    ['Database Design: Normalization, ERD và Migration Strategy', 'Từ ER diagram đến production schema với zero-downtime migration.'],
  ],
  'SECURITY' => [
    ['Ethical Hacking & Penetration Testing A-Z', 'Reconnaissance, exploitation, privilege escalation và reporting với Kali Linux.'],
    ['Web Application Security: OWASP Top 10 thực chiến', 'SQLi, XSS, CSRF, SSRF — từ exploit đến fix với Burp Suite.'],
    ['Cloud Security: AWS Security Specialty Certification Prep', 'IAM policies, VPC security, GuardDuty, Security Hub và compliance.'],
    ['DevSecOps: Tích hợp Security vào CI/CD Pipeline', 'SAST, DAST, SCA, secret scanning và policy-as-code với OPA.'],
  ],
  'DEVOPSUB' => [
    ['DevOps Roadmap: Docker, Kubernetes và CI/CD Pipeline', 'Containerization, orchestration, GitOps với ArgoCD và GitHub Actions.'],
    ['GitLab CI/CD: Từ Pipeline cơ bản đến Advanced Deployments', 'Merge request pipelines, environments, review apps và Helm charts.'],
    ['Platform Engineering: Internal Developer Platform với Backstage', 'Golden paths, service catalog và self-service infrastructure.'],
    ['SRE: Site Reliability Engineering Thực chiến', 'SLO/SLI/SLA, error budget, toil reduction và postmortem culture.'],
    ['Linux System Administration: Từ Basics đến Production', 'Systemd, networking, security hardening và performance tuning.'],
  ],
  'CLOUD' => [
    ['AWS Solutions Architect Associate: SAA-C03 Lý thuyết và Lab', 'VPC, EC2, RDS, S3, CloudFront, ECS/EKS và well-architected framework.'],
    ['AWS DevOps Professional: Lộ trình Thi và Thực hành', 'CodePipeline, CodeDeploy, Systems Manager và advanced monitoring.'],
    ['Google Cloud Professional Data Engineer: Chứng chỉ và Lab', 'BigQuery, Dataflow, Pub/Sub, Vertex AI và data governance.'],
    ['Azure Administrator AZ-104: Toàn diện từ A đến Z', 'Virtual networks, Azure AD, App Service, AKS và Azure Monitor.'],
    ['Serverless Architecture: AWS Lambda, API Gateway và DynamoDB', 'Event-driven design, SAM, cold start optimization và observability.'],
    ['Multi-Cloud Architecture: AWS, GCP và Azure Best Practices', 'Vendor lock-in avoidance, Terraform multi-cloud và compliance.'],
  ],
  'K8S' => [
    ['Kubernetes từ cơ bản đến Production: CKA Certification Prep', 'Pod lifecycle, networking, storage, RBAC và cluster upgrade strategies.'],
    ['Helm & Kubernetes Operators: Package và Automate K8s', 'Helm chart development, CRD, operator pattern với Operator SDK.'],
    ['Service Mesh với Istio: Zero-Trust Network trong K8s', 'mTLS, traffic management, observability và circuit breaker patterns.'],
  ],
  'IaC' => [
    ['Terraform: Infrastructure as Code từ A đến Z', 'HCL, modules, state management, workspaces và Terragrunt patterns.'],
    ['Ansible: Configuration Management và Automation', 'Playbooks, roles, Ansible Vault và AWX/Tower cho enterprise.'],
    ['Pulumi: Cloud Infrastructure với Python và TypeScript', 'Reuse language skills cho IaC, stack references và testing.'],
  ],
  'PYTHON' => [
    ['Python 3.12: Từ Cơ bản đến Lập trình hướng Đối tượng', 'Syntax, functions, OOP, decorators, context managers và packaging.'],
    ['Python Advanced: Concurrency, Metaprogramming và Performance', 'asyncio, threading, multiprocessing, Cython và profiling tools.'],
    ['Python cho Automation: Scripting và DevOps Tasks', 'File handling, APIs, web scraping, email và schedule automation.'],
    ['Data Analysis với Python: Pandas và NumPy Chuyên sâu', 'DataFrame operations, time series, advanced indexing và visualization.'],
  ],
  'JSTYPE' => [
    ['JavaScript ES2024: Từ cơ bản đến Modern JS', 'Closures, promises, generators, modules và latest ECMAScript features.'],
    ['TypeScript Complete Guide: Types, Generics và Advanced Patterns', 'Type narrowing, conditional types, decorators và tsconfig mastery.'],
    ['Node.js Performance Engineering: Worker Threads và Clustering', 'V8 internals, memory leaks, profiling và horizontal scaling.'],
  ],
  'GO' => [
    ['Go Programming Language: Từ Zero đến Gopher', 'Syntax, structs, interfaces, goroutines, channels và testing.'],
    ['Advanced Go: Concurrency Patterns và Performance', 'sync primitives, context propagation, pprof và escape analysis.'],
    ['Building CLIs và Tools với Go và Cobra', 'Cobra framework, configuration, logging và cross-compile distribution.'],
  ],
  'RUST' => [
    ['Rust Programming Language: Ownership và Systems Programming', 'Borrow checker, lifetimes, traits, error handling và unsafe Rust.'],
    ['Rust for Web: Axum, SeaORM và Production Deployment', 'Async Rust, tower services, tracing và containerized deployment.'],
  ],
  'JAVA' => [
    ['Java 21 & Spring Boot 3: Enterprise Development', 'Virtual threads, records, pattern matching, Spring Security và JPA.'],
    ['Spring Cloud Microservices: Config, Discovery và Gateway', 'Eureka, Config Server, Resilience4j và distributed tracing với Zipkin.'],
  ],
  'RUBY' => [
    ['Ruby on Rails 7.2: Full-Stack Development Masterclass', 'ActiveRecord, Action Cable, Active Job, Turbo và Stimulus JS.'],
    ['Advanced Ruby: Metaprogramming và Design Patterns', 'method_missing, Refinements, Module patterns và Ruby gems development.'],
  ],
  'ENG' => [
    ['English Grammar Mastery: Từ B1 đến C1 một cách hệ thống', 'Tenses, conditionals, passive voice và advanced sentence structures.'],
    ['English Conversation: Từ Intermediate đến Fluent', 'Shadowing technique, idioms, phrasal verbs và cultural fluency.'],
    ['Business English Communication: Email, Meeting và Presentation', 'Professional writing, meeting facilitation và public speaking.'],
    ['English Pronunciation: Accent Reduction và Phonetics', 'IPA symbols, minimal pairs, connected speech và intonation.'],
    ['Academic English Writing: Research Papers và Reports', 'Essay structure, argument building, citation và academic vocabulary.'],
  ],
  'IELTS' => [
    ['IELTS Academic: Lộ trình đạt 7.0+ trong 3 tháng', 'Chiến lược từng kỹ năng, band descriptors và practice tests với feedback.'],
    ['IELTS Writing Task 2: Từ 5.5 lên 8.0', 'Essay types, coherence, lexical resource và grammatical range strategies.'],
    ['TOEIC 900+: Listening và Reading Mastery', 'Part strategies, vocabulary domains và timed practice với analytics.'],
    ['TOEIC Speaking & Writing: Đạt điểm cao với Chiến lược', 'Pronunciation scoring, template answers và vocabulary building.'],
  ],
  'JPN' => [
    ['JLPT N5 & N4: Nền tảng Tiếng Nhật từ Đầu hoàn toàn', 'Hiragana, Katakana, Kanji cơ bản, ngữ pháp và hội thoại hàng ngày.'],
    ['JLPT N3: Ngữ pháp và Từ vựng Toàn diện', 'Grammar patterns N3, reading comprehension và listening strategies.'],
    ['JLPT N2 Masterclass: Đọc hiểu và Ngữ pháp Nâng cao', 'Complex grammar, keigo introduction, speed reading và mock tests.'],
    ['Tiếng Nhật Thương mại: Keigo và Văn phong Công sở', 'Business emails, meeting language, self-introduction và presentation.'],
    ['Tiếng Nhật Giao tiếp Hàng ngày: Tự học nhanh trong 6 tháng', 'Shadowing, pronunciation drills và situational dialogues.'],
  ],
  'KOR' => [
    ['TOPIK I: Tiếng Hàn cho Người mới hoàn toàn', 'Hangul, pronunciation, basic grammar và everyday conversation.'],
    ['TOPIK II: Ngữ pháp và Từ vựng Trung-Nâng cao', 'Intermediate grammar, reading essays, formal writing và mock exams.'],
    ['Tiếng Hàn Giao tiếp: K-Pop, K-Drama và Văn hóa', 'Informal speech, honorifics basics và cultural immersion approach.'],
    ['Korean Business Language: Môi trường Làm việc Hàn Quốc', 'Business etiquette, formal correspondence và company culture.'],
  ],
  'CHN' => [
    ['HSK 1-3: Tiếng Trung Cơ bản Toàn diện', 'Pinyin, tones, basic characters, grammar và HSK vocabulary lists.'],
    ['HSK 4-6: Tiếng Trung Nâng cao và Luyện thi Chứng chỉ', 'Complex grammar, formal writing, listening comprehension và mock tests.'],
    ['Tiếng Trung Kinh doanh: Thương mại và Đàm phán', 'Business vocabulary, negotiation phrases và formal correspondence.'],
  ],
  'BIZENG' => [
    ['Business English for IT Professionals', 'Technical presentations, requirement gathering và stakeholder communication.'],
    ['English for Finance & Accounting: CFA và Report Writing', 'Financial terminology, analysis reports và investor communication.'],
  ],
  'DS' => [
    ['Data Science với Python: Pandas, Seaborn và Scikit-Learn', 'EDA, feature engineering, modeling pipeline và stakeholder reporting.'],
    ['Statistics for Data Science: Probability và Hypothesis Testing', 'Distributions, CLT, A/B testing và Bayesian inference.'],
    ['A/B Testing và Experimentation: Thiết kế và Phân tích', 'Power analysis, statistical significance, novelty effect và reporting.'],
    ['Data Storytelling: Visualization với Matplotlib và Seaborn', 'Chart selection, narrative structure và executive dashboards.'],
    ['Causal Inference: Beyond Correlation trong Data Science', 'DAGs, RCT, DID, synthetic control và instrumental variables.'],
  ],
  'DE' => [
    ['Data Engineering với Apache Spark và Delta Lake', 'Batch/streaming processing, Spark optimization và lakehouse patterns.'],
    ['Modern Data Stack: dbt, Airflow và Snowflake', 'ELT pipelines, data modeling với dbt và orchestration patterns.'],
    ['Kafka: Event Streaming từ cơ bản đến Distributed Systems', 'Producers, consumers, Kafka Streams, Connect và schema registry.'],
    ['Real-time Data Engineering với Flink và Iceberg', 'Stateful stream processing, exactly-once semantics và OLAP tables.'],
  ],
  'BI' => [
    ['Power BI Complete: Từ Beginner đến Data Analyst Professional', 'DAX fundamentals, advanced calculations, dataflows và gateway.'],
    ['Tableau Desktop Specialist: Visualization và Dashboard', 'Calculated fields, LOD expressions, actions và Tableau Prep.'],
    ['Looker Studio & GA4: Marketing Analytics Dashboard', 'Connected sheets, blended data và advanced segmentation.'],
    ['Advanced Excel for Data Analysis: Power Query và PivotTable', 'M language, DAX trong Power Pivot và dynamic arrays.'],
  ],
  'DA' => [
    ['SQL for Data Analysts: Window Functions và Advanced Queries', 'CTEs, WINDOW, PIVOT, recursive queries và query optimization.'],
    ['Google Analytics 4: Thu thập và Phân tích dữ liệu Web', 'Event tracking, custom dimensions, BigQuery export và attribution.'],
    ['Marketing Analytics: Customer Lifetime Value và Cohort', 'RFM analysis, churn prediction và campaign attribution modeling.'],
  ],
  'STOCKS' => [
    ['Đầu tư Chứng khoán Cơ bản: Từ Zero đến Nhà đầu tư', 'Các loại chứng khoán, cách mở tài khoản, đọc bảng giá và đặt lệnh.'],
    ['Quản lý Danh mục Đầu tư và Quản lý Rủi ro', 'Modern Portfolio Theory, diversification, correlation và rebalancing.'],
    ['Đầu tư Bất động sản: Phân tích và Định giá', 'Cash flow analysis, cap rate, tỷ lệ sinh lời và financing strategies.'],
  ],
  'TA' => [
    ['Phân tích Kỹ thuật Toàn diện: Từ Candlestick đến Elliott Wave', 'Chart patterns, indicators, Volume Profile và trading plan.'],
    ['Price Action Trading: Chiến lược Không cần Indicator', 'Support/resistance, supply/demand, Smart Money Concepts và backtest.'],
    ['Algorithmic Trading với Python: Backtesting và Live Trading', 'Backtrader, zipline, broker API integration và risk management.'],
  ],
  'FA' => [
    ['Phân tích Cơ bản: Định giá Cổ phiếu và Báo cáo Tài chính', 'P/E, P/B, DCF, đọc BCTC và xây dựng financial model.'],
    ['Financial Modeling: DCF, LBO và M&A Analysis', 'Excel financial models, sensitivity analysis và investment memos.'],
    ['CFA Level 1: Lộ trình Học và Luyện đề Hiệu quả', 'Ethics, FRA, Equity, FI, Derivatives — chiến lược thi và mock exams.'],
  ],
  'PF' => [
    ['Quản lý Tài chính Cá nhân: Xây dựng Nền tảng Tự do Tài chính', 'Budgeting, emergency fund, debt payoff và investment allocation.'],
    ['Thoát bẫy Nợ và Xây dựng Vốn từ Đầu', 'Debt snowball/avalanche, credit score và wealth-building mindset.'],
    ['Kế hoạch Tài chính cho Gia đình Trẻ', 'Insurance, education fund, retirement planning và estate basics.'],
  ],
  'ACCTG' => [
    ['Kế toán Doanh nghiệp: Từ Nghiệp vụ đến Báo cáo Tài chính', 'Double-entry bookkeeping, GAAP/VAS và financial statements prep.'],
    ['Kế toán Thuế: Quyết toán Thuế TNDN và TNCN', 'Tax forms, declarations, audit preparation và tax optimization.'],
    ['Phân tích Báo cáo Tài chính cho Nhà đầu tư', 'Quality of earnings, red flags, segment analysis và comparables.'],
  ],
  'DMKTG' => [
    ['Digital Marketing A-Z: SEO, SEM, Social Media và Email', 'Xây dựng digital presence toàn diện từ strategy đến execution.'],
    ['Facebook Ads Mastery: Scaling từ 0 đến 100 triệu/tháng', 'Audience research, creative testing, retargeting và scaling strategies.'],
    ['Google Ads Performance Max và Search Campaigns', 'Keyword strategy, bidding, ad copy testing và attribution.'],
    ['TikTok Marketing: Viral Content và Paid Ads Strategy', 'TikTok algorithm, content calendar và in-feed ad optimization.'],
    ['Email Marketing với Mailchimp và ActiveCampaign', 'List building, automation sequences, segmentation và deliverability.'],
  ],
  'SEO' => [
    ['SEO Masterclass: On-page, Off-page và Technical SEO', 'Keyword research, link building, Core Web Vitals và schema markup.'],
    ['SEO cho E-commerce: Tăng Organic Traffic và Doanh thu', 'Product page optimization, faceted navigation và international SEO.'],
    ['Local SEO: Đưa Doanh nghiệp lên Google Maps và Top tìm kiếm', 'GMB optimization, citation building và review management.'],
  ],
  'SMM' => [
    ['Social Media Marketing: Xây dựng Thương hiệu trên Mạng xã hội', 'Content strategy, community management và social listening.'],
    ['Instagram Marketing: từ 0 đến 100K Followers', 'Reels strategy, hashtag research, stories và collaboration.'],
    ['LinkedIn Marketing cho B2B: Lead Generation và Personal Brand', 'Profile optimization, content pillars và Sales Navigator.'],
  ],
  'CONTENT' => [
    ['Content Marketing Strategy: Xây dựng Thương hiệu Cá nhân', 'Content calendar, SEO writing, repurposing và distribution.'],
    ['Copywriting Masterclass: Viết lời quảng cáo chuyển đổi cao', 'AIDA, PAS, landing page copy và A/B testing frameworks.'],
  ],
  'BRAND' => [
    ['Brand Strategy: Xây dựng Thương hiệu từ Đầu', 'Brand identity, positioning, messaging framework và brand book.'],
    ['Marketing Analytics: Đo lường ROI và Attribution', 'UTM, multi-touch attribution, MMM và marketing mix optimization.'],
  ],
  'UXUI' => [
    ['UI/UX Design Masterclass: Figma từ Cơ bản đến Expert', 'Wireframes, prototyping, auto-layout, components và dev handoff.'],
    ['UX Research: Methods, Analysis và Reporting', 'Interviews, usability testing, card sorting và research repositories.'],
    ['Design Systems: Xây dựng và Duy trì Component Library', 'Tokens, atomic design, documentation và Storybook integration.'],
    ['Mobile UX: iOS và Android Human Interface Guidelines', 'Platform-specific patterns, accessibility và responsive design.'],
    ['UX Writing: Microcopy và Content Design', 'Voice and tone, error messages, onboarding và localization.'],
  ],
  'GDESIGN' => [
    ['Adobe Photoshop CC: Retouching và Composite Masterclass', 'Layer masking, frequency separation, color grading và smart objects.'],
    ['Adobe Illustrator CC: Vector Design và Illustration', 'Pen tool mastery, type manipulation, packaging design và logo.'],
    ['Brand Identity Design: Logo, Typography và Color System', 'Brand brief, logo construction, type pairing và brand application.'],
    ['Social Media Design với Canva Pro: Templates và Automation', 'Brand kit, Magic Resize, bulk create và Canva API integration.'],
  ],
  'MOTION' => [
    ['After Effects CC: Motion Graphics và Visual Effects', 'Keyframing, expressions, shape layers và 3D space in AE.'],
    ['Motion Design System: Xây dựng Animated Brand Identity', 'Kinetic typography, logo animation và motion principles.'],
  ],
  'PDESIGN' => [
    ['Product Design: Từ Research đến High-Fidelity Prototype', 'Design sprint, jobs-to-be-done, interaction design và hand-off.'],
    ['Figma Advanced: Variables, Prototyping và Dev Mode', 'Component properties, variables, conditional logic và smart animate.'],
  ],
  'VIDED' => [
    ['Adobe Premiere Pro CC: Video Editing Chuyên nghiệp', 'Multi-cam editing, color workspace, audio mixing và export.'],
    ['DaVinci Resolve: Color Grading và Professional Post-Production', 'Node-based grading, Fusion VFX, Fairlight audio và delivery.'],
    ['YouTube Content Creation: Từ Ý tưởng đến 100K Subscribers', 'Scripting, filming setup, editing workflow và growth strategy.'],
    ['Cinematic Filmmaking: Storytelling và Camera Techniques', 'DP fundamentals, color theory, sound design và short film.'],
  ],
  'PHOTO' => [
    ['Nhiếp ảnh Cơ bản: Từ Auto đến Manual Mode Tự tin', 'Exposure triangle, composition rules, white balance và RAW editing.'],
    ['Portrait Photography: Ánh sáng và Hướng dẫn Subject', 'Natural light, studio lighting, posing và Lightroom retouching.'],
  ],
  'PM' => [
    ['Product Management Fundamentals: Từ Idea đến Launch', 'Discovery, prioritization, roadmap, metrics và stakeholder management.'],
    ['Agile Product Owner: Scrum, Backlog và Sprint Planning', 'User stories, acceptance criteria, ceremonies và velocity tracking.'],
    ['Product Analytics: Data-Driven Decision Making', 'Funnel analysis, retention, North Star metric và product experimentation.'],
    ['Go-to-Market Strategy: Định giá, Kênh và Product Launch', 'Market sizing, competitive analysis, launch playbook và GTM metrics.'],
  ],
  'BIZSTRAT' => [
    ['Lean Startup: Validate Ý tưởng và Build MVP', 'Business Model Canvas, customer development, pivot và product-market fit.'],
    ['Chiến lược Kinh doanh: Từ Porter đến Blue Ocean', 'Competitive advantage, value chain, strategy maps và OKRs.'],
    ['Negotiation Skills: Đàm phán Win-Win Chuyên nghiệp', 'BATNA, anchoring, interest-based negotiation và cross-cultural.'],
  ],
  'PROJMGMT' => [
    ['PMP Certification Prep: Thi và Thực hành Project Management', 'PMBOK 7, agile hybrid, stakeholder management và risk planning.'],
    ['Quản lý Dự án với Notion và Jira', 'Workspace setup, sprint boards, reporting và team workflows.'],
  ],
  'AGILE' => [
    ['Scrum Master Professional: CSM Prep và Coaching Skills', 'Scrum events, artifacts, servant leadership và impediment removal.'],
    ['SAFe Agile: Scaled Agile Framework cho Doanh nghiệp', 'PI Planning, ARTs, value streams và Lean Portfolio Management.'],
  ],
  'ROBOT' => [
    ['ROS2 Robotics: Xây dựng Robot Autonomous từ Đầu', 'Nodes, topics, services, Nav2 và robot simulation với Gazebo.'],
    ['SLAM và Path Planning cho Mobile Robot', 'Cartographer, AMCL, costmaps và dynamic obstacle avoidance.'],
  ],
  'IOT' => [
    ['Arduino và Raspberry Pi: IoT Project thực tế từ Đầu', 'Sensors, actuators, MQTT, InfluxDB và Grafana dashboard.'],
    ['ESP32 và MicroPython: Wireless IoT Development', 'WiFi, BLE, deep sleep, OTA update và MQTT broker setup.'],
  ],
  'COMM' => [
    ['Giao tiếp Chuyên nghiệp: Từ Ngại ngùng đến Tự tin', 'Active listening, body language, assertiveness và difficult conversations.'],
    ['Kỹ năng Thuyết trình: Nói trước đám đông Không run', 'Structure, visual aids, handling Q&A và online presentation.'],
  ],
  'LEADER' => [
    ['Leadership Fundamentals: Từ Individual Contributor đến Manager', 'Situational leadership, delegation, feedback và performance management.'],
    ['Emotional Intelligence: EQ cho Lãnh đạo Hiện đại', 'Self-awareness, empathy, conflict resolution và psychological safety.'],
  ],
  'MINDSET' => [
    ['Tư duy Phản biện và Giải quyết Vấn đề', 'Logical fallacies, structured problem solving và decision frameworks.'],
    ['Quản lý Thời gian: Deep Work và Productivity System', 'Time blocking, GTD, Eisenhower matrix và digital minimalism.'],
  ],
}.freeze
