# =============================================================================
# QUIZ QUESTION TEMPLATES (by topic area)
# =============================================================================

QUIZ_QUESTIONS = {
  tech: [
    { q: 'Điều gì xảy ra khi bạn gọi `git rebase` thay vì `git merge`?',
      opts: ['Tạo một merge commit mới', 'Viết lại lịch sử commit để linear hóa', 'Xóa các branch cũ', 'Đồng bộ remote với local'],
      correct: 1, difficulty: 'medium' },
    { q: 'SOLID trong lập trình hướng đối tượng viết tắt của gì?',
      opts: ['Single responsibility, Open/closed, Liskov, Interface segregation, Dependency inversion',
             'Simple, Organized, Layered, Independent, Dynamic',
             'Scalable, Object-oriented, Logical, Integrated, Distributed',
             'Service, Object, Library, Interface, Design'],
      correct: 0, difficulty: 'medium' },
    { q: 'Trong REST API, HTTP method nào nên được dùng để cập nhật một phần tài nguyên?',
      opts: ['PUT', 'POST', 'PATCH', 'UPDATE'], correct: 2, difficulty: 'easy' },
    { q: 'Big O notation O(log n) thường liên quan đến thuật toán nào?',
      opts: ['Linear search', 'Binary search', 'Bubble sort', 'DFS'],
      correct: 1, difficulty: 'easy' },
    { q: 'Dependency Injection giải quyết vấn đề gì?',
      opts: ['Cải thiện hiệu năng', 'Giảm coupling giữa các class', 'Tăng tốc độ compile', 'Giảm memory usage'],
      correct: 1, difficulty: 'medium' },
    { q: 'Trong microservices, Pattern nào giải quyết vấn đề distributed transaction?',
      opts: ['Circuit Breaker', 'CQRS', 'Saga', 'Event Sourcing'],
      correct: 2, difficulty: 'hard' },
    { q: 'Indexing trong database giúp cải thiện điều gì?',
      opts: ['Write performance', 'Read performance', 'Storage efficiency', 'Data integrity'],
      correct: 1, difficulty: 'easy' },
    { q: 'CAP Theorem phát biểu rằng một distributed system không thể đồng thời đảm bảo?',
      opts: ['Consistency, Availability, Performance',
             'Consistency, Availability, Partition tolerance',
             'Correctness, Availability, Persistence',
             'Concurrency, Atomicity, Performance'],
      correct: 1, difficulty: 'hard' },
    { q: 'Docker container khác với Virtual Machine ở điểm nào chính?',
      opts: ['Container không có OS riêng, share kernel với host', 'Container chậm hơn VM', 'Container dùng nhiều RAM hơn', 'Container không thể chạy trên Linux'],
      correct: 0, difficulty: 'easy' },
    { q: 'JWT token gồm mấy phần được phân tách bởi dấu chấm?',
      opts: ['2', '3', '4', '5'], correct: 1, difficulty: 'easy' },
    { q: 'WebSocket khác HTTP thông thường ở điểm gì?',
      opts: ['Nhanh hơn về speed', 'Cho phép giao tiếp hai chiều real-time', 'Dùng ít bandwidth hơn', 'Không cần TCP/IP'],
      correct: 1, difficulty: 'medium' },
    { q: 'N+1 query problem thường xảy ra khi?',
      opts: ['Query quá phức tạp', 'Không dùng index', 'Load associations riêng lẻ cho từng record', 'Dùng ORM thay vì raw SQL'],
      correct: 2, difficulty: 'medium' },
  ],
  ml: [
    { q: 'Overfitting xảy ra khi model?',
      opts: ['Không học được patterns từ training data', 'Học quá kỹ training data, không generalize được', 'Có quá ít parameters', 'Được train quá ít epochs'],
      correct: 1, difficulty: 'easy' },
    { q: 'Cross-validation giúp làm gì?',
      opts: ['Tăng tốc độ training', 'Đánh giá model trên nhiều subset để giảm variance trong evaluation', 'Giảm số parameters', 'Tăng kích thước dataset'],
      correct: 1, difficulty: 'medium' },
    { q: 'Regularization L1 (Lasso) có tác dụng đặc biệt gì so với L2?',
      opts: ['Nhanh hơn', 'Tạo sparse weights (nhiều coefficients = 0)', 'Giảm bias', 'Tăng learning rate'],
      correct: 1, difficulty: 'hard' },
    { q: 'Gradient descent cập nhật weights bằng cách nào?',
      opts: ['Cộng learning rate với gradient', 'Trừ learning rate nhân với gradient', 'Nhân weights với gradient', 'Chia weights cho gradient'],
      correct: 1, difficulty: 'medium' },
    { q: 'Trong classification, F1-Score là gì?',
      opts: ['Accuracy trung bình', 'Harmonic mean của Precision và Recall', 'Tổng Precision và Recall', 'Precision chia Recall'],
      correct: 1, difficulty: 'medium' },
    { q: 'Batch Normalization giúp neural network như thế nào?',
      opts: ['Giảm số layers', 'Ổn định quá trình training, cho phép learning rate cao hơn', 'Loại bỏ dropout', 'Tăng model capacity'],
      correct: 1, difficulty: 'hard' },
    { q: 'Transfer Learning hoạt động dựa trên nguyên tắc gì?',
      opts: ['Dùng nhiều GPU hơn', 'Sử dụng lại features đã học từ task/domain khác', 'Tăng dataset size', 'Giảm model complexity'],
      correct: 1, difficulty: 'easy' },
    { q: 'Attention mechanism trong Transformer giải quyết vấn đề gì của RNN?',
      opts: ['Training speed', 'Long-range dependencies và vanishing gradient', 'Memory usage', 'Interpretability'],
      correct: 1, difficulty: 'hard' },
    { q: 'Principal Component Analysis (PCA) dùng để làm gì?',
      opts: ['Classification', 'Dimensionality reduction', 'Clustering', 'Regression'],
      correct: 1, difficulty: 'easy' },
    { q: 'k-fold Cross Validation với k=5 có nghĩa là?',
      opts: ['Train 5 models', 'Chia data thành 5 phần, mỗi lần dùng 1 phần để validate', 'Train 5 epochs', 'Dùng 5% data để test'],
      correct: 1, difficulty: 'medium' },
  ],
  finance: [
    { q: 'P/E ratio (Price-to-Earnings) cho biết điều gì?',
      opts: ['Doanh thu công ty', 'Nhà đầu tư trả bao nhiêu cho 1 đồng lợi nhuận', 'Tỷ lệ nợ trên vốn', 'Tăng trưởng doanh thu'],
      correct: 1, difficulty: 'easy' },
    { q: 'Đường hỗ trợ (Support) trong phân tích kỹ thuật là gì?',
      opts: ['Đường giá cao nhất', 'Mức giá mà áp lực mua đủ mạnh để ngăn giá giảm tiếp', 'Đường trung bình động', 'Mức kháng cự'],
      correct: 1, difficulty: 'easy' },
    { q: 'Diversification trong đầu tư giúp giảm loại rủi ro nào?',
      opts: ['Systematic risk (market risk)', 'Unsystematic risk (company-specific)', 'Inflation risk', 'Liquidity risk'],
      correct: 1, difficulty: 'medium' },
    { q: 'Beta của cổ phiếu = 1.5 có nghĩa là?',
      opts: ['Cổ phiếu tăng 150% mỗi năm', 'Cổ phiếu biến động 1.5 lần so với thị trường', 'P/E bằng 1.5', 'Lợi nhuận 1.5%/năm'],
      correct: 1, difficulty: 'medium' },
    { q: 'Candlestick màu xanh (bullish) cho thấy điều gì?',
      opts: ['Giá đóng cửa thấp hơn giá mở cửa', 'Giá đóng cửa cao hơn giá mở cửa', 'Không có giao dịch', 'Volume cao'],
      correct: 1, difficulty: 'easy' },
    { q: 'DCF (Discounted Cash Flow) valuation dựa trên nguyên tắc nào?',
      opts: ['So sánh với peer companies', 'Giá trị hiện tại của tất cả cash flows tương lai', 'Giá trị sổ sách', 'Doanh thu × multiple'],
      correct: 1, difficulty: 'hard' },
    { q: 'Stop Loss trong trading có mục đích gì?',
      opts: ['Tối đa hóa lợi nhuận', 'Giới hạn lỗ khi trade đi ngược chiều', 'Tăng position size', 'Lock lợi nhuận'],
      correct: 1, difficulty: 'easy' },
    { q: 'RSI (Relative Strength Index) trên 70 thường được hiểu là?',
      opts: ['Oversold, cơ hội mua', 'Overbought, có thể sắp điều chỉnh', 'Trend mạnh, tiếp tục mua', 'Không có ý nghĩa'],
      correct: 1, difficulty: 'medium' },
  ],
  english: [
    { q: 'Which sentence uses the Present Perfect correctly?',
      opts: ['I have went to Paris last year.', 'She has lived here since 2010.', 'They have finished the work yesterday.', 'He has went to school.'],
      correct: 1, difficulty: 'medium' },
    { q: 'What does the idiom "break the ice" mean?',
      opts: ['To damage frozen water', 'To start a conversation in an awkward situation', 'To end a relationship', 'To solve a problem quickly'],
      correct: 1, difficulty: 'easy' },
    { q: 'Choose the correct form: "If I _____ rich, I would travel the world."',
      opts: ['am', 'was', 'were', 'be'], correct: 2, difficulty: 'medium' },
    { q: 'In Academic IELTS Writing Task 1, what should the first sentence include?',
      opts: ['Personal opinion', 'Paraphrased overview of the diagram', 'Direct copy of the question', 'Main trend description'],
      correct: 1, difficulty: 'hard' },
    { q: 'What is the passive voice of "The team completed the project"?',
      opts: ['The project was completed by the team.', 'The project is completed.', 'The team was completing the project.', 'The project has been completing.'],
      correct: 0, difficulty: 'easy' },
    { q: 'Which word best completes: "The new policy will _____ the company\'s growth"?',
      opts: ['prohibit', 'facilitate', 'complicate', 'neglect'],
      correct: 1, difficulty: 'medium' },
    { q: 'In formal business writing, which phrase is most appropriate?',
      opts: ["I wanna know...", "Could you please provide...", "Hey, send me...", "Gimme the details on..."],
      correct: 1, difficulty: 'easy' },
  ],
  japanese: [
    { q: 'What does the particle 「は」 (wa) indicate?',
      opts: ['Object of the verb', 'Topic of the sentence', 'Location', 'Direction'],
      correct: 1, difficulty: 'easy' },
    { q: '「先生に会いたい」means?',
      opts: ['I met the teacher', 'I want to meet the teacher', 'The teacher wants to meet', 'I talked to the teacher'],
      correct: 1, difficulty: 'medium' },
    { q: 'JLPT N2で「〜ざるを得ない」の意味は何ですか？',
      opts: ['したくない', 'しなければならない（仕方なく）', 'してはいけない', 'できる'],
      correct: 1, difficulty: 'hard' },
    { q: 'Which is the correct polite form of 食べる (to eat)?',
      opts: ['食べます', '食べている', '食べた', '食べる'], correct: 0, difficulty: 'easy' },
    { q: '「申し訳ございません」はビジネス場面でどういう意味ですか？',
      opts: ['ありがとうございます', '大変失礼しました（深い謝罪）', 'よろしくお願いします', 'お世話になります'],
      correct: 1, difficulty: 'medium' },
  ],
  marketing: [
    { q: 'AIDA trong Marketing viết tắt của gì?',
      opts: ['Awareness, Interest, Design, Action', 'Attention, Interest, Desire, Action', 'Analysis, Intent, Data, Analytics', 'Audience, Insight, Design, Awareness'],
      correct: 1, difficulty: 'easy' },
    { q: 'CTR (Click-Through Rate) được tính bằng công thức nào?',
      opts: ['Impressions / Clicks × 100', 'Clicks / Impressions × 100', 'Conversions / Clicks', 'Revenue / Ad Spend'],
      correct: 1, difficulty: 'easy' },
    { q: 'Customer Acquisition Cost (CAC) tốt khi nào?',
      opts: ['CAC > LTV (Lifetime Value)', 'CAC < LTV', 'CAC = LTV', 'CAC không liên quan đến LTV'],
      correct: 1, difficulty: 'medium' },
    { q: 'Trong SEO, backlinks quan trọng vì?',
      opts: ['Tăng tốc website', 'Là tín hiệu authority và trust với Google', 'Giảm bounce rate', 'Tăng CTR từ SERP'],
      correct: 1, difficulty: 'medium' },
    { q: 'A/B testing trong marketing dùng để làm gì?',
      opts: ['Test 2 phiên bản để tìm ra version hiệu quả hơn', 'Test phần A và B của campaign', 'So sánh 2 đối thủ', 'Test trên 2 nền tảng khác nhau'],
      correct: 0, difficulty: 'easy' },
    { q: 'ROAS (Return on Ad Spend) = 400% nghĩa là?',
      opts: ['Lợi nhuận 400% trên chi phí quảng cáo', 'Cứ 1đ bỏ ra quảng cáo, thu về 4đ doanh thu', 'Tỷ lệ chuyển đổi 4%', 'Tăng trưởng 400%'],
      correct: 1, difficulty: 'medium' },
  ],
}.freeze

# ── MODULE & LESSON TITLE TEMPLATES ──────────────────────────────────────────

MODULE_LESSON_TEMPLATES = {
  intro:      { module: 'Tổng quan và Giới thiệu Khóa học',
                lessons: ['Giới thiệu khóa học và lộ trình học', 'Cài đặt môi trường phát triển', 'Tổng quan về công cụ và tài nguyên', 'Hello World và chạy thử đầu tiên'] },
  fundamentals: { module: 'Kiến thức Nền tảng',
                  lessons: ['Các khái niệm cơ bản cần nắm', 'Cú pháp và cấu trúc căn bản', 'Kiểu dữ liệu và biến', 'Luồng điều khiển và vòng lặp', 'Hàm và module hóa code'] },
  core1:      { module: 'Core Concepts Phần 1',
                lessons: ['Khái niệm trung tâm đầu tiên', 'Cách hoạt động bên dưới hood', 'Pattern phổ biến và best practices', 'Ví dụ thực tế từ industry', 'Workshop thực hành'] },
  core2:      { module: 'Core Concepts Phần 2',
                lessons: ['Mở rộng kiến thức nền', 'Advanced patterns', 'Xử lý edge cases', 'Performance considerations', 'Code review và refactoring'] },
  advanced:   { module: 'Nâng cao và Thực chiến',
                lessons: ['Kiến trúc hệ thống thực tế', 'Tối ưu hóa và scaling', 'Security và best practices', 'Testing và CI/CD', 'Monitoring và observability'] },
  project1:   { module: 'Dự án Thực hành 1: Xây dựng từ Đầu',
                lessons: ['Phân tích yêu cầu và thiết kế', 'Xây dựng foundation', 'Implement core features', 'UI/UX và integration', 'Testing và deployment'] },
  project2:   { module: 'Dự án Thực hành 2: Nâng cấp và Mở rộng',
                lessons: ['Thêm tính năng nâng cao', 'Tích hợp third-party services', 'Performance optimization', 'Production deployment', 'Review và next steps'] },
  qa:         { module: 'Ôn tập và Luyện đề',
                lessons: ['Tổng ôn kiến thức toàn khóa', 'Câu hỏi thường gặp trong phỏng vấn', 'Mock interview và practice', 'Tài nguyên tiếp tục học'] },
}.freeze

TOPIC_MODULES = {
  web: [
    { module: 'HTTP, DNS và Web Architecture', lessons: ['HTTP/HTTPS và request lifecycle', 'DNS lookup và domain', 'Client-Server model', 'Web servers: Nginx và Apache'] },
    { module: 'Authentication & Authorization', lessons: ['Session vs Token authentication', 'JWT: tạo và xác thực', 'OAuth 2.0 và OpenID Connect', 'Role-based access control', 'Security best practices'] },
    { module: 'Database Integration', lessons: ['ORM fundamentals', 'CRUD operations', 'Migrations và schema design', 'Query optimization', 'Connection pooling'] },
    { module: 'API Design & Development', lessons: ['RESTful API principles', 'Versioning strategies', 'Error handling conventions', 'Rate limiting và throttling', 'API documentation với Swagger'] },
    { module: 'Testing và Quality Assurance', lessons: ['Unit testing fundamentals', 'Integration testing', 'End-to-end testing', 'Test-driven development', 'CI/CD pipeline setup'] },
    { module: 'Deployment và Production', lessons: ['Containerization với Docker', 'Environment configuration', 'Continuous deployment', 'Monitoring và logging', 'Performance tuning'] },
  ],
  ml: [
    { module: 'Data Preparation và EDA', lessons: ['Import và khám phá dữ liệu', 'Xử lý missing values', 'Feature scaling và encoding', 'Visualization với Matplotlib', 'Correlation analysis'] },
    { module: 'Supervised Learning', lessons: ['Linear và Logistic Regression', 'Decision Trees và Random Forest', 'SVM và Kernel trick', 'Gradient Boosting (XGBoost, LightGBM)', 'Model evaluation metrics'] },
    { module: 'Model Tuning và Validation', lessons: ['Train/Val/Test split', 'Cross-validation strategies', 'Hyperparameter tuning với Optuna', 'Bias-variance tradeoff', 'Learning curves'] },
    { module: 'Neural Networks Fundamentals', lessons: ['Perceptron và forward pass', 'Backpropagation', 'Activation functions', 'Loss functions', 'Optimizer: SGD, Adam, AdaGrad'] },
    { module: 'Deployment và MLOps', lessons: ['Model serialization', 'REST API với FastAPI', 'Docker packaging', 'MLflow tracking', 'Monitoring model drift'] },
  ],
  finance: [
    { module: 'Thị trường Tài chính Cơ bản', lessons: ['Các loại thị trường tài chính', 'Cổ phiếu, trái phiếu và phái sinh', 'Cơ chế khớp lệnh', 'Các loại lệnh giao dịch', 'Thuế và phí giao dịch'] },
    { module: 'Đọc và Phân tích Báo cáo Tài chính', lessons: ['Bảng cân đối kế toán', 'Báo cáo kết quả kinh doanh', 'Báo cáo lưu chuyển tiền tệ', 'Các chỉ số tài chính quan trọng', 'Red flags trong BCTC'] },
    { module: 'Phân tích Kỹ thuật Cơ bản', lessons: ['Đọc biểu đồ candlestick', 'Trend, Support và Resistance', 'Moving Averages', 'RSI, MACD và Stochastic', 'Volume analysis'] },
    { module: 'Quản lý Vốn và Rủi ro', lessons: ['Position sizing', 'Risk/Reward ratio', 'Stop loss và take profit', 'Portfolio diversification', 'Drawdown management'] },
    { module: 'Xây dựng Chiến lược Giao dịch', lessons: ['Định nghĩa trading plan', 'Backtesting chiến lược', 'Journal giao dịch', 'Psychology of trading', 'Review và optimize'] },
  ],
  english: [
    { module: 'Foundation: Grammar Essentials', lessons: ['Tenses: Simple, Continuous, Perfect', 'Modal verbs và expressions', 'Conditionals: 0, 1, 2, 3', 'Passive voice', 'Reported speech'] },
    { module: 'Vocabulary Building', lessons: ['Collocations và fixed expressions', 'Academic vocabulary (AWL)', 'Business và professional vocabulary', 'Phrasal verbs in context', 'Word formation: prefixes, suffixes'] },
    { module: 'Listening Skills', lessons: ['Identifying main ideas', 'Note-taking techniques', 'Inference và implication', 'Accents và varieties', 'IELTS/TOEIC listening strategies'] },
    { module: 'Reading Comprehension', lessons: ['Skimming và scanning', 'Identifying text structure', 'Understanding academic texts', 'True/False/Not Given strategies', 'Speed reading techniques'] },
    { module: 'Writing Skills', lessons: ['Paragraph structure', 'Essay types và formats', 'Cohesion và coherence', 'Academic tone và style', 'Editing và proofreading'] },
    { module: 'Speaking Confidence', lessons: ['Pronunciation fundamentals', 'Fluency techniques', 'Discussion và debate', 'Presentation skills', 'IELTS speaking strategies'] },
  ],
  japanese: [
    { module: 'Chữ viết và Phát âm', lessons: ['Hiragana 46 âm', 'Katakana và ứng dụng', 'Kanji cơ bản N5 (100 chữ)', 'Phát âm đặc trưng tiếng Nhật', 'Pitch accent cơ bản'] },
    { module: 'Ngữ pháp N5', lessons: ['Cấu trúc câu cơ bản', 'Particles: は、が、を、に、で', 'Động từ nhóm 1, 2, 3', 'Thể lịch sự (Masu form)', 'Adjectives: i-adj và na-adj'] },
    { module: 'Ngữ pháp N4', lessons: ['Te-form và ứng dụng', 'Potential, volitional forms', 'Conditional: たら、ば、と、なら', 'Causative và Passive', 'Expressions of giving/receiving'] },
    { module: 'Từ vựng và Kanji N3', lessons: ['Kanji N3 core 300 chữ', 'Từ vựng chủ đề: công việc', 'Từ vựng chủ đề: xã hội', 'Compound words', 'Kango vs Wago'] },
    { module: 'Hội thoại Thực tế', lessons: ['Tự giới thiệu chuyên nghiệp', 'Xin phép và từ chối lịch sự', 'Shopping và dịch vụ', 'Đặt phòng và ăn uống', 'Hỏi đường và giao thông'] },
  ],
}.freeze

# Avatar URLs pool (realistic Unsplash/Pravatar style)
AVATAR_URLS = (1..70).map { |i| "https://i.pravatar.cc/300?img=#{i}" }.freeze

# Thumbnail URLs pool (topic images from picsum)
THUMBNAIL_URLS = (1..200).map { |i| "https://picsum.photos/seed/course#{i}/640/360" }.freeze

# YouTube video IDs (real educational videos, safe to use in seeds)
YOUTUBE_IDS = %w[
  dQw4w9WgXcQ M7lc1UVf-VE J---aiyznGQ kJQP7kiw5Fk uD4izuDMUQA
  8jPQjjsBbIc RgKAFK5djSk CevxZvSJLk8 9bZkp7q19f0 YQHsXMglC9A
  tgbNymZ7vqY fJ9rUzIMcZQ OPf0YbXqDm0 hT_nvWreIhg VYOjWnS4cMY
  pRpeEdMmmQ0 60ItHLz5WEA JGwWNGJdvx8 09R8_2nJtjg HSHTWFOhCyY
  7KZuZpMaFlo V-_Oal4tWec nfWlot6h_JM xvFZjo5PgG0 r3XuBMSa4kY
].freeze

puts "  [#{elapsed}s]  ── Question templates loaded"
$stdout.flush
